# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    forward_position_controller:
      type: forward_position_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - slewing_joint
      - trolley_joint
      - hook_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity