controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - slewing_joint
        - trolley_joint
        - hook_joint
      use_local_topics: false

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - slewing_joint
        - trolley_joint
        - hook_joint
      interface_name: position
