options:
  dcf_path: "/home/labcrane/appdata/ws_tower_crane/install/tower_crane/share/tower_crane/config/robot_control"

master:
  node_id: 127
  name: "master"
  driver: "ros2_canopen::MasterDriver"
  package: canopen_master_driver
  sync_period: 10000

slewing_joint:
  node_id: 3
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  dcf: "DSY-C.EDS"
  period: 10
  heartbeat_producer: 1000
  sdo:
    - {index: 0x6060, sub_index: 0, value: 1}
    - {index: 0x6040, sub_index: 0, value: 0x0F}
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}
        - {index: 0x606C, sub_index: 0}
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x607A, sub_index: 0}

trolley_joint:
  node_id: 2
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  dcf: "DSY-C.EDS"
  period: 10
  heartbeat_producer: 1000
  sdo:
    - {index: 0x6060, sub_index: 0, value: 1}
    - {index: 0x6040, sub_index: 0, value: 0x0F}
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}
        - {index: 0x606C, sub_index: 0}
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x607A, sub_index: 0}

hook_joint:
  node_id: 1
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  dcf: "DSY-C.EDS"
  period: 10
  heartbeat_producer: 1000
  sdo:
    - {index: 0x6060, sub_index: 0, value: 1}
    - {index: 0x6040, sub_index: 0, value: 0x0F}
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}
        - {index: 0x606C, sub_index: 0}
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x607A, sub_index: 0}
