options:
  dcf_path: "/home/qiaoqiaochen/appdata/canros/install/tower_crane/share/tower_crane/config/robot_control"
  # dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000
  boot_time: 500

defaults:
  node_id: 0
  namespace: "/roscan"
  dcf: "dchcan.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  boot: true
  enable_lazy_load: true
  polling: false
  period: 10
  scale_pos_to_dev: 2607.5946
  scale_pos_from_dev: 0.0003835
  scale_vel_to_dev: 26075.946
  scale_vel_from_dev: 0.00003835
  velocity_mode: 1
  sdo:
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x6083, sub_index: 0, value: 2000}
    - {index: 0x6084, sub_index: 0, value: 2000}
    - {index: 0x6060, sub_index: 0, value: 3}
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6041, sub_index: 0} # status word
       - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6069, sub_index: 0} # position actual value
       - {index: 0x6064, sub_index: 0} # velocity actual pvalue
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # Controlword
      - {index: 0x60FF, sub_index: 0} # Target velocity

nodes:
  trolley_motor:
    node_id: 1
  hoist_motor:
    node_id: 3
  slewing_motor:
    node_id: 2