options:
  dcf_path: "/home/qiaoqiaochen/appdata/canros/install/tower_crane/share/tower_crane/config/robot_control"
  # dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000
  boot_time: 500

defaults:
  node_id: 0
  namespace: "/roscan"
  dcf: "dchcan.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  boot: true
  enable_lazy_load: true
  polling: false
  period: 10
  scale_pos_to_dev: 2607.5946
  scale_pos_from_dev: 0.0003835
  scale_vel_to_dev: 26075.946
  scale_vel_from_dev: 0.00003835
  velocity_mode: 1
  sdo:
    - {index: 0x6081, sub_index: 0, value: 10}
    - {index: 0x6083, sub_index: 0, value: 200}
    - {index: 0x6084, sub_index: 0, value: 500}
    - {index: 0x60F9, sub_index: 1, value: 400}
    - {index: 0x60F9, sub_index: 2, value: 200}
    - {index: 0x6085, sub_index: 0, value: 50}
    - {index: 0x6098, sub_index: 0, value: 0}
    - {index: 0x60C2, sub_index: 1, value: 50}
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}
        - {index: 0x6061, sub_index: 0}
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}
        - {index: 0x606C, sub_index: 0}
    3:
      enabled: false
    4:
      enabled: false
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}
        - {index: 0x6060, sub_index: 0}
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x607A, sub_index: 0}
        - {index: 0x60FF, sub_index: 0}

nodes:
  trolley_motor:
    node_id: 1
  hoist_motor:
    node_id: 3
  slewing_motor:
    node_id: 2