options:
  dcf_path: "/home/qiaoqiaochen/appdata/canros/install/tower_crane/share/tower_crane/config/robot_control"
  disable_bootstrap: true

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000
  boot_time: 500

defaults:
  node_id: 0
  namespace: "/roscan"
  dcf: "dchcan.eds"
  driver: "ros2_canopen::Cia402Driver"
  period: 10
  position_mode: 1
  revision_number: 0
  boot_timeout_ms: 20000
  sdo_timeout_ms: 10000
  boot: false
  reset_communication: false
  # fake: true
  sdo:
    - {index: 0x60C2, sub_index: 1, value: 50}
    - {index: 0x60C2, sub_index: 2, value: -3}
    - {index: 0x6083, sub_index: 0, value: 2000}
    - {index: 0x6084, sub_index: 0, value: 2000}
    - {index: 0x6060, sub_index: 0, value: 10}
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6041, sub_index: 0} # status word
       - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6069, sub_index: 0} # position actual value
       - {index: 0x6064, sub_index: 0} # velocity actual pvalue
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # Controlword
      - {index: 0x60FF, sub_index: 0} # Target velocity

trolley_motor:
  node_id: 1
  namespace: "/roscan"
  package: "canopen_402_driver"
  boot: true
  enable_lazy_load: true
  polling: false
  period: 10
  position_mode: 1
  revision_number: 0
  boot_timeout_ms: 20000
  sdo_timeout_ms: 10000
  boot: false
  reset_communication: false
  sdo:
    - {index: 0x60C2, sub_index: 1, value: 50}
    - {index: 0x60C2, sub_index: 2, value: -3}
    - {index: 0x6083, sub_index: 0, value: 2000}
    - {index: 0x6084, sub_index: 0, value: 2000}
    - {index: 0x6060, sub_index: 0, value: 10}
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6041, sub_index: 0} # status word
       - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6069, sub_index: 0} # position actual value
       - {index: 0x6064, sub_index: 0} # velocity actual pvalue
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # Controlword
      - {index: 0x60FF, sub_index: 0} # Target velocity

hoist_motor:
  node_id: 3
  namespace: "/roscan"
  package: "canopen_402_driver"
  dcf: "DSY-C.EDS"
  driver: "ros2_canopen::Cia402Driver"
  period: 10
  position_mode: 1
  revision_number: 0
  boot_timeout_ms: 20000
  sdo_timeout_ms: 10000
  boot: false
  reset_communication: false
  sdo:
    - {index: 0x60C2, sub_index: 1, value: 50}
    - {index: 0x60C2, sub_index: 2, value: -3}
    - {index: 0x6083, sub_index: 0, value: 2000}
    - {index: 0x6084, sub_index: 0, value: 2000}
    - {index: 0x6060, sub_index: 0, value: 10}
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6041, sub_index: 0} # status word
       - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
       - {index: 0x6069, sub_index: 0} # position actual value
       - {index: 0x6064, sub_index: 0} # velocity actual pvalue
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # Controlword
      - {index: 0x60FF, sub_index: 0} # Target velocity
